### ISSUE TITLE
Missing attributes

### ISSUE THREAD

**Issue by WilcoFiers** [A11yance/aria-query#18]
I couldn't quite figure out if this was intentional or not, but three of the ARIA 1.1 props aren't defined (as in, they are listed in some of the roles, but they're not included in the `ariaPropsMap`. It certainly doesn't seem intentional. The three props are  `aria-details`, `aria-errormessage` and `aria-describedat`.

**Comment by jkodu** [comment]
The below snippet helps narrow down the three missing attributes.

```js
const { roles, aria: props } = require('aria-query');
const propNames = Array.from(props).map(([key]) => key);
const allProps = Array.from(roles).reduce((out, [name, rule]) => {
  return [...out, ...Object.keys(rule.props)];
}, []);
const undocumentedProps  = allProps.filter(prop => !propNames.includes(prop));
console.log(undocumentedProps);
```

Output:
[ 'aria-details', 'aria-errormessage', 'aria-describeat' ]

**Comment by jessebeach** [comment]
I knew that `aria-errormessage` is missing. I didn't know about `aria-details` and `aria-describedat`. Thank you for pointing them out.

**Comment by mcking65** [comment]
aria-describeat didn't make into aria 1.1

**Comment by WilcoFiers** [comment]
`aria-describedat` is listed in the DPUB roles.

**Comment by mcking65** [comment]
the [DPUB ARIA module spec](https://www.w3.org/TR/dpub-aria-1.0/) includes only role definitions. It does not include states or properties.

All DPUB roles have the doc- prefix, not the aria- prefix, which is reserved for aria states and properties.

**Comment by WilcoFiers** [comment]
Sorry, I wasn't very clear there. I know how the DPUB ARIA module works. What I'm saying is that in aria-query, if you get the props that are available on the DPUB roles, you'll see the `aria-describedat` property. It isn't actually part of the DPUB module, so that it's included in aria-query seems to be a bug.

**Comment by jessebeach** [comment]
Good point, @WilcoFiers .

**Comment by kurosawa-takeshi** [comment]
As far as I know, the problem is 

- definitions of aria-query are based on [an old DPUB-ARIA working draft](https://www.w3.org/TR/2016/WD-dpub-aria-1.0-20160317/) which incorporate states and props of [an old WAI-ARIA 1.1 working drafts](https://www.w3.org/TR/2015/WD-wai-aria-1.1-20151119/) so that aria-query has aria-describedat,
- [The latest DPUB-ARIA recommendation](https://www.w3.org/TR/2017/REC-dpub-aria-1.0-20171214/) incorporates states and props of [the latest WAI-ARIA 1.1 Recommendation](https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/) so that both of them dropped aria-describedat.

I think, thus, definitions of aria-query should be updated to latest recommendations.

**Comment by jessebeach** [comment]
@WilcoFiers, @marcysutton what do you think about targeting this for the aXe Hackathon at CSUN?

**Comment by marcysutton** [comment]
@jessebeach what do you think is the level of effort for this? The time at the hackathon always goes by so fast.

**Comment by kurosawa-takeshi** [comment]
@jessebeach @marcysutton 

I opened pull requests [removing  aria-describedat from dpub-aria](https://github.com/A11yance/aria-query/pull/20), [adding aria-details](https://github.com/A11yance/aria-query/pull/21) and [adding double-checking tests](https://github.com/A11yance/aria-query/pull/22).

I apologize that I didn't mention I've started working on this in the previous comment.

If you don't mind, could you review them and please let me know if there are any problems.

(Though I won't attend CSUN, the Hackathon must be fun 😄 .)

**Comment by jessebeach** [comment]
@kurosawa-takeshi I apologize for causing you extra work because this project lacks documentation. No one else was working on it but me at the start.

The files under `src/etc` are generated by a script: `node ./scripts/breakUpAriaJSON.js`. This script reads `./scripts/roles.json` and then generates all the files. You should edit roles.json with the correct values. The script does a lot of magic to figure out inheritance, dedupe props, etc. 

I updated the README.

Yay tests!

**Comment by jessebeach** [comment]
@kurosawa-takeshi resolved this issue. Thank you! 💯
