### ISSUE TITLE
Drop Node 8 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [A11yance/aria-query#45]
Because it's [EOL](https://nodejs.org/en/about/releases).

**Comment by jessebeach** [comment]
@ljharb has strong opinions on this topic and I've gotten on this particular bandwagon because it doesn't seem to have a significant downside. What's the case for dropping support?

**Comment by ljharb** [comment]
Specifically, imo EOL status is irrelevant; packages should support what people use.

Separately, if i'm stuck on node 8, and packages don't support node 8, then it makes it harder to upgrade node because there's more things i'll likely have to update. Nobody's staying on old node versions because packages "let" them - they're doing it because they have no other choice.

**Comment by jessebeach** [comment]
We'll keep the status quo for now.
