### ISSUE TITLE
Implicit `code` role for `code` element

### ISSUE THREAD

**Issue by MatanBobi** [A11yance/aria-query#463]
Hi!
As a follow up for https://github.com/testing-library/dom-testing-library/issues/1100
It looks like the ARIA spec added an implicit role `code` for the `code` HTML element.
![image](https://user-images.githubusercontent.com/12711091/209861527-51755c8f-e847-45ad-b296-6d12e25b745a.png)
https://www.w3.org/TR/html-aria/

We'd be happy for a fix here so we'll also get it in testing-library :)
Thanks for your help! :)

**Comment by timdeschryver** [comment]
@MatanBobi if I'm not mistaken this will be available in the next version.
The PR https://github.com/A11yance/aria-query/pull/447 should've fixed it.
Because an issue from dom-testing-library is mentioned, I wanted to piggy back on this and also mention another issue https://github.com/testing-library/dom-testing-library/issues/1201 which will also be fixed.

**Comment by MatanBobi** [comment]
Yeah @timdeschryver, I missed that because I was only looking at the README of this project and it didn't mention `code` role so I guess this should also be updated. And yeah it looks like the other should also be resolved :) Thanks for catching this.
