### ISSUE TITLE
Specification version clarification

### ISSUE THREAD

**Issue by cmorten** [A11yance/aria-query#498]
In the README it says:

> Programmatic access to the [WAI-ARIA 1.2 Roles Model](https://raw.githack.com/w3c/aria/stable/#roles). This package tracks the stable editor's draft (last update: 21 July 2020).

However the link takes you to a WAI-ARIA 1.3 spec page. Is this repo now tracking 1.3 editor’s draft, or is the link incorrect?

Appreciate any clarification!

**Comment by jessebeach** [comment]
> 



> In the README it says:
> 
> > Programmatic access to the [WAI-ARIA 1.2 Roles Model](https://raw.githack.com/w3c/aria/stable/#roles). This package tracks the stable editor's draft (last update: 21 July 2020).
> 
> However the link takes you to a WAI-ARIA 1.3 spec page. Is this repo now tracking 1.3 editor’s draft, or is the link incorrect?
> 
> Appreciate any clarification!

We're tracking 1.2 right now. I think they changed the content under the link and updated the spec.

**Comment by jlp-craigmorten** [comment]
@jessebeach I've amended #499 to update the README link to reflect.

---

FYI there are a few definitions in this project that fall into WAI-ARIA 1.3 and aren't available in WAI-ARIA 1.2:

- [`aria-braillelabel` property attribute](http://raw.githack.com/w3c/aria/master/index.html#aria-braillelabel)
- [`aria-brailleroledescription` property attribute](http://raw.githack.com/w3c/aria/master/index.html#aria-brailleroledescription)
- [`aria-description` property attribute](http://raw.githack.com/w3c/aria/master/index.html#aria-description)
- [`mark` role](http://raw.githack.com/w3c/aria/master/index.html#mark)

These appear to have snuck in following the audit done in #447 of https://www.w3.org/TR/html-aam-1.0/, unfortunately being a working draft it seems they have accidentally referenced roles and attributes that are in the Editor's Draft for WAI-ARIA 1.3 and not WAI-ARIA 1.2.

Happy to raise a PR to remove the above so that this project tracks 1.2 correctly?

**Comment by jessebeach** [comment]
@jlp-craigmorten updated the link is a good change. 

At the same time, having these extra aria props and the role defined isn't doing any damage. This values are going to land with the 1.3 version of the spec. If you're using them now, then you're just a little ahead of the curve, so there's no reason not to validate them. In other words, they're not changing any behavior in 1.2; they're just adding behavior.
