### ISSUE TITLE
5.2 regression - `elementRoles` no longer works when `undefined` is passed

### ISSUE THREAD

**Issue by boris-petrov** [A11yance/aria-query#507]
I'm using [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint/) and it started blowing up with `aria-query` 5.2.1. It breaks on this line:

```js
let implicitRoles = elementRoles.get(elementRoles.keys().find((key) => key.name === element))
```

`elementRoles.keys().find((key) => key.name === element)` returns `undefined` so `get` is called with `undefined`. That used to work in 5.1.3 (and returned `undefined`).

**Comment by jessebeach** [comment]
@boris-petrov what is the specific value for the `key`? 

`elementRoles.keys().find` will return undefined if it finds nothing. If `element` doesn't match any `key.name`, then `find` will return `undefined` and get will try to find `undefined`. 

[ember-template-lint](https://github.com/ember-template-lint/ember-template-lint/) was never passing in the right type to the `get` method. In v5.0.2, the method looked like this:

https://github.com/A11yance/aria-query/blob/7f1fd66c5ebd3ca9d455cc7a6fee4eccd96c384d/src/elementRoleMap.js#L62-L67

The method expects an `ARIARoleRelationConcept`, which is defined here.

https://github.com/A11yance/aria-query/blob/7f1fd66c5ebd3ca9d455cc7a6fee4eccd96c384d/flow/aria.js#L335-L344

The implementation in ember-template-lint *happened* to work because in aria-query@v5.0.2, the argument is passed to `JSON.stringify`, which would have returned "undefined" as a string.

In aria-query@5.2.1, the signature of the get method is unchanged, but the internal implementation is updated. If you pass in the same expected shape, it will return the same expected shape.

https://github.com/A11yance/aria-query/blob/f9f9ea6cbd239122e69539c36654fa1456398180/src/elementRoleMap.js#L68-L73

This implementation will explode if `undefined` is pass to the method, but `undefined` is an invalid type to pass to the method, so the error is expected.

This is a bug for ember-template-lint and their implementation of their rule. Feel free to link them here :) Here's how they can fix it:

```
if (element != null) {
  const implicitRoles = elementRoles.get(element);
  return implicitRoles && implicitRoles[0];
}
return null;
```

**Comment by boris-petrov** [comment]
Thank you for the detailed response! I thought it might be a bug on their side but anyway wanted to mention that this is a change in behavior in `aria-query`. I'll let them know, thanks!
