### ISSUE TITLE
`elementRoleMaps` includes conflicting mapping for complementary

### ISSUE THREAD

**Issue by khiga8** [A11yance/aria-query#526]
Hi! I'm looking at [__tests__/src/elementRoleMap-test.js](https://github.com/A11yance/aria-query/blob/main/__tests__/src/elementRoleMap-test.js), and I noticed that the entries for `elementRoleMaps` includes both:

```code
[{"name": "aside"}, ["complementary"]],
```

and later

```code
[{"name": "aside"}, ["generic"]],
```

These seem to conflict with each other. 

Should `[{"name": "aside"}, ["complementary"]]` be removed? I think this is coming from [complementaryRole.js](https://github.com/A11yance/aria-query/blob/main/src/etc/roles/literal/complementaryRole.js).

Tangentially, which document should I be looking at as the source of truth? I saw both https://www.w3.org/TR/html-aam-1.0/ and https://www.w3.org/TR/wai-aria-1.2/#roles referenced, and wasn't sure which one. Thank you!

**Comment by jlp-craigmorten** [comment]
See below for some relevant references to specifications.

I've been known to get muddled between these specifications but my understanding is that:

- HTML AAM indicates that the `aside` HTML element will be exposed by user agents to assistive technologies as one of two roles depending on it's scope:
    1. Role `complementary` if scoped to the `body` or a `main` element, or if scoped to sectioning content (aka scoped to a `header` or `footer` element) _and_ it has an accessible name.
    2. Role `generic` if scoped to sectioning content (aka scoped to a `header` or `footer` element) _and_ it does not have an accessible name.
- HTML ARIA indicates that the `aside` HTML element has an implicit `complementary` role.

These don't appear to be quite aligned.

Assuming user agents are actually conforming to the HTML-AAM specification in how they expose the `aside` HTML element (and that this is the desired behaviour), it feels like HTML-ARIA needs an update to explain that the implicit role for the `aside` HTML element can also be `generic` depending on the scope (indeed the implicit ARIA semantics are stated to be defined in HTML AAM for this section of HTML ARIA).

There appears to be an open issue tracking this in the HTML ARIA repo already.

So afaik this project is documenting the element role mappings somewhat correctly. There is perhaps room for improvement as it appears to be missing the constraints for the `scoped to the body or main element` variation of `aside` being given a role of `complementary`.

See also:

- https://github.com/w3c/html-aam/issues/512
- https://github.com/w3c/html-aam/pull/350
- https://github.com/w3c/html-aria/issues/411

---

## HTML ARIA

> This specification defines the authoring rules (author conformance requirements) for the use of [Accessible Rich Internet Applications (WAI-ARIA) 1.2](https://www.w3.org/TR/wai-aria-1.2/) and [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria-1.0/) attributes on [[HTML](https://www.w3.org/TR/html-aria/#bib-html)] elements.

### 4. Document conformance requirements for use of ARIA attributes in HTML 

> The following table provides normative per-element document conformance requirements for the use of ARIA markup in HTML documents. Additionally, it identifies the [implicit ARIA semantics](https://www.w3.org/TR/wai-aria-1.2/#implicit_semantics) that apply to [HTML elements](https://html.spec.whatwg.org/multipage/infrastructure.html#html-elements). The [implicit ARIA semantics](https://www.w3.org/TR/wai-aria-1.2/#implicit_semantics) of these elements are defined in [HTML AAM](https://www.w3.org/TR/html-aria/#bib-html-aam-1.0).

| HTML element | Implicit ARIA semantics (explicitly assigning these in markup is NOT RECOMMENDED) | ARIA role, state and property allowances  |
| :--- | :--- | :--- |
[aside](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element) | role=[complementary](https://www.w3.org/TR/html-aria/#index-aria-complementary) | Roles: [feed](https://www.w3.org/TR/html-aria/#index-aria-feed), [none](https://www.w3.org/TR/html-aria/#index-aria-none), [note](https://www.w3.org/TR/html-aria/#index-aria-note), [presentation](https://www.w3.org/TR/html-aria/#index-aria-presentation), [region](https://www.w3.org/TR/html-aria/#index-aria-region) or [search](https://www.w3.org/TR/html-aria/#index-aria-search). ([complementary](https://www.w3.org/TR/html-aria/#index-aria-complementary) is also allowed, but NOT RECOMMENDED.)<br><br>DPub Roles: [doc-dedication](https://www.w3.org/TR/dpub-aria-1.0/#doc-dedication), [doc-example](https://www.w3.org/TR/dpub-aria-1.0/#doc-example), [doc-footnote](https://www.w3.org/TR/dpub-aria-1.0/#doc-footnote), [doc-glossary](https://www.w3.org/TR/dpub-aria-1.0/#doc-glossary), [doc-pullquote](https://www.w3.org/TR/dpub-aria-1.0/#doc-pullquote) or [doc-tip](https://www.w3.org/TR/dpub-aria-1.0/#doc-tip)<br><br>[Global aria-* attributes](https://www.w3.org/TR/wai-aria-1.2/#global_states) and any aria-* attributes applicable to the allowed roles.|

REF: https://www.w3.org/TR/html-aria/#docconformance

## HTML AAM

> HTML Accessibility API Mappings (HTML-AAM) defines how [user agents](https://infra.spec.whatwg.org/#user-agent) map HTML [[HTML](https://www.w3.org/TR/html-aam-1.0/#bib-html)] elements and attributes to platform [accessibility application programming interfaces (APIs)](https://www.w3.org/TR/wai-aria/#dfn-accessibility-api).

### 3.4.8 aside (scoped to the body or main element)

| HTML Specification | [aside](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element) (scoped to the body or main element) |
| :--- | :--- |
| [[wai-aria-1.2](https://www.w3.org/TR/html-aam-1.0/#bib-wai-aria-1.2)] | [complementary](https://www.w3.org/TR/core-aam-1.2/#role-map-complementary) role |

REF: https://www.w3.org/TR/html-aam-1.0/#el-aside-ancestorbodymain

### 3.4.9 aside (scoped to a sectioning content element)

| HTML Specification | [aside](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element) (scoped to a [sectioning content](https://html.spec.whatwg.org/multipage/dom.html#sectioning-content) element) |
| :--- | :--- |
| [[wai-aria-1.2](https://www.w3.org/TR/html-aam-1.0/#bib-wai-aria-1.2)] | [complementary](https://www.w3.org/TR/core-aam-1.2/#role-map-complementary) role if the [aside](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element) element has an [accessible name](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name). Otherwise, [generic](https://www.w3.org/TR/core-aam-1.2/#role-map-generic) role. |

REF: https://www.w3.org/TR/html-aam-1.0/#el-aside
